(function(global){'use strict';LF.ready(function(){var page=document.body.dataset.page;if(page==='dashboard')dashboard();if(page==='messages')messages();if(page==='notifications')notifications();if(page==='leaderboard')leaderboard();if(page==='login')login();if(page==='settings')settings();
function esc(v){var e=document.createElement('span');e.textContent=String(v||'');return e.innerHTML;}
function dashboard(){var reports=LF.store.get('reports',[]),claims=LF.store.get('claims',[]),box=document.querySelector('[data-my-records]'),all=reports.concat(claims);box.innerHTML=all.length?all.map(function(r){return '<article class="record-row"><div><p class="mono meta">'+esc(r.id)+'</p><h3 class="h4">'+esc(r.title||r.itemTitle||r.itemId)+'</h3><p class="meta">'+esc(r.building||r.slot||'Saved in this browser')+'</p></div><span class="status-chip" data-status="'+esc(r.status||'reported')+'">'+esc(r.status||'reported')+'</span></article>';}).join(''):'<div class="state state--compact"><svg class="icon state__glyph"><use href="#i-inbox"></use></svg><h3 class="state__title">No personal records yet</h3><p class="state__desc">Reports and claims made on this device will appear here.</p><div class="state__actions"><a class="btn btn--primary" href="report-lost.html">Report an item</a></div></div>';}
function messages(){var buttons=document.querySelectorAll('.thread-link'),title=document.querySelector('[data-thread-title]');buttons.forEach(function(b){b.addEventListener('click',function(){buttons.forEach(function(x){x.setAttribute('aria-selected','false');});b.setAttribute('aria-selected','true');title.textContent=b.dataset.title;});});var form=document.querySelector('.composer');form.addEventListener('submit',function(e){e.preventDefault();var input=form.elements.message;if(!input.value.trim())return;var p=document.createElement('p');p.className='message message--mine';p.textContent=input.value;document.querySelector('.conversation__body').appendChild(p);LF.store.push('messages',{id:Date.now(),text:input.value});input.value='';p.scrollIntoView();});}
function notifications(){LF.api.notifications().then(function(rows){var read=LF.store.get('readNotifications',[]),box=document.querySelector('[data-notices]');box.innerHTML=rows.map(function(n){var isRead=n.read||read.indexOf(n.id)>=0;return '<article class="notice" data-id="'+n.id+'" data-read="'+isRead+'"><svg class="icon"><use href="#i-'+(n.kind==='match'?'search':n.kind==='claim'?'shield-check':'bell')+'"></use></svg><div><h3 class="h4">'+esc(n.title)+'</h3><p>'+esc(n.body)+'</p><small>'+esc(n.time)+'</small></div><button class="btn btn--sm btn--ghost" type="button" data-read-one '+(isRead?'disabled':'')+'>Mark read</button></article>';}).join('');LF.enhance(box);box.addEventListener('click',function(e){var btn=e.target.closest('[data-read-one]');if(!btn)return;var row=btn.closest('.notice');LF.store.toggle('readNotifications',row.dataset.id);row.dataset.read='true';btn.disabled=true;});});}
function leaderboard(){LF.api.users().then(function(users){document.querySelector('[data-leaders]').innerHTML=users.sort(function(a,b){return b.points-a.points;}).map(function(u){return '<article class="leader-row"><span class="avatar">'+esc(u.initials)+'</span><div><h3 class="h4">'+esc(u.name)+'</h3><p class="meta">'+esc(u.faculty)+'</p></div><div><strong class="mono">'+u.returned+'</strong> returned</div><strong class="mono">'+u.points+' pts</strong></article>';}).join('');});}
function login(){var form=document.querySelector('[data-login]');form.addEventListener('submit',function(e){e.preventDefault();var email=form.elements.email,msg=document.getElementById('email-error');if(!/@(?:student\.)?university\.edu$/i.test(email.value)){email.setAttribute('aria-invalid','true');msg.textContent='Use your university.edu campus email.';return;}LF.store.set('session',{email:email.value,name:'Campus member'});location.href='dashboard.html';});}
function settings(){document.querySelectorAll('[data-setting]').forEach(function(input){input.checked=LF.store.get('setting.'+input.dataset.setting,input.checked);input.addEventListener('change',function(){LF.store.set('setting.'+input.dataset.setting,input.checked);});});}}
);})(window);
