(function(global){
  'use strict';
  LF.ready(function(){
    var form=document.querySelector('[data-report-form]'); if(!form)return;
    var kind=form.dataset.reportForm, step=1, panels=Array.from(form.querySelectorAll('.flow-panel')), steps=Array.from(document.querySelectorAll('.stepper__step')), duplicate=document.querySelector('[data-duplicates]');
    function show(n,scroll){step=n;panels.forEach(function(p,i){p.hidden=i!==n-1;});steps.forEach(function(s,i){s.dataset.state=i<n-1?'done':i===n-1?'current':'todo';s.setAttribute('aria-current',i===n-1?'step':'false');});if(scroll!==false)document.querySelector('.flow-form').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});if(n===3)summary();}
    function validate(){var ok=true;panels[step-1].querySelectorAll('[required]').forEach(function(input){var msg=document.getElementById(input.getAttribute('aria-describedby'));if(!input.value.trim()){input.setAttribute('aria-invalid','true');if(msg)msg.textContent='This field is required.';ok=false;}else{input.removeAttribute('aria-invalid');if(msg)msg.textContent='';}});return ok;}
    function summary(){var data=new FormData(form), box=document.querySelector('[data-summary]');box.innerHTML=['title','category','colour','building','date','description'].map(function(k){var v=data.get(k);return v?'<div class="flow-summary__row"><dt>'+label(k)+'</dt><dd>'+escape(v)+'</dd></div>':'';}).join('');}
    function label(k){return {title:'Item',category:'Category',colour:'Colour',building:'Building',date:kind==='lost'?'Date lost':'Date found',description:'Description'}[k]||k;}
    function escape(v){var x=document.createElement('span');x.textContent=v;return x.innerHTML;}
    form.addEventListener('click',function(e){var next=e.target.closest('[data-next]'),back=e.target.closest('[data-back]');if(next&&validate())show(Math.min(3,step+1));if(back)show(Math.max(1,step-1));});
    form.addEventListener('input',function(e){if(e.target.hasAttribute('aria-invalid'))validate();if(kind==='lost'&&(e.target.name==='title'||e.target.name==='category'))checkDuplicates();});
    function checkDuplicates(){var title=form.elements.title.value.toLowerCase(),category=form.elements.category.value;if(title.length<3&&!category){duplicate.hidden=true;return;}LF.api.items().then(function(items){var matches=items.filter(function(i){return i.kind==='found'&&((category&&i.category===category)||(title&&i.title.toLowerCase().split(' ').some(function(w){return w.length>3&&title.indexOf(w)>=0;})));}).slice(0,2);duplicate.hidden=!matches.length;if(matches.length)duplicate.querySelector('[data-duplicate-list]').innerHTML=matches.map(function(i){return '<a class="duplicate-link" href="item.html?id='+encodeURIComponent(i.id)+'"><img src="'+LF.root+i.image+'" alt=""><span><strong>'+escape(i.title)+'</strong><small>'+escape(i.buildingName)+'</small></span></a>';}).join('');});}
    form.addEventListener('submit',function(e){e.preventDefault();if(!validate())return;var data=Object.fromEntries(new FormData(form).entries()),ref=(kind==='lost'?'LR-':'FR-')+String(Date.now()).slice(-6);data.id=ref;data.kind=kind;data.createdAt=new Date().toISOString();LF.store.push('reports',data,'id');form.innerHTML='<div class="state"><svg class="icon state__glyph"><use href="#i-check"></use></svg><h2 class="state__title">Report received</h2><p class="state__desc">Your reference is <strong class="mono">'+ref+'</strong>. We will keep this report in this browser and notify you when a possible match appears.</p><div class="state__actions"><a class="btn btn--primary" href="dashboard.html">View my reports</a><a class="btn btn--secondary" href="browse.html">Browse registry</a></div></div>';LF.enhance(form);});
    show(1,false);
  });
})(window);
